### ISSUE TITLE
是否有打算进行beta版本汉化?

### ISSUE THREAD

**Issue by ANGJustinl** [xiyuesaves/translation-module#1]
steam公开版本为0.756.4 而目前最新版本为0.760.97
ui进行了破坏性的调整
作者链接 https://www.patreon.com/BreedersOfTheNephelym

**Comment by xiyuesaves** [comment]
目前所有高于 0.756.4 的版本均无法使用汉化模组，根据作者的说法，在UI重构完成之前都不会支持多语言切换功能。

**Comment by ANGJustinl** [comment]
oo thx :D
